### ISSUE TITLE
Conflicts with enum members

### ISSUE THREAD

**Issue by infinityplusb** [Syniurge/Calypso#100]
Hi, me again

I've moved on from the previous errors [#99](https://github.com/Syniurge/Calypso/issues/99) but haven't managed to compile anything error-free yet! 

I've added in a few more includes into [my project](https://github.com/infinityplusb/opencv_test) but the latest errors I am getting is that it is having conflicts with 
```
brian@spoke:~/Documents/Programming/d/opencv_test$ ldc2 -cpp-args -std=c++11 test_opencv.d core/*.d
Error: variable ℂcpp._.FP_NORMAL conflicts with enum member ℂcpp._.FP_NORMAL at /usr/include/math.h(223)
Error: variable ℂcpp._.FP_SUBNORMAL conflicts with enum member ℂcpp._.FP_SUBNORMAL at /usr/include/math.h(220)
Error: variable ℂcpp._.FP_ZERO conflicts with enum member ℂcpp._.FP_ZERO at /usr/include/math.h(217)
Error: variable ℂcpp._.FP_INFINITE conflicts with enum member ℂcpp._.FP_INFINITE at /usr/include/math.h(214)
Error: variable ℂcpp._.FP_NAN conflicts with enum member ℂcpp._.FP_NAN at /usr/include/math.h(211)
```
None of the conflicting variables appear anywhere in the code, so I'm unsure where it is getting these from. Also none of my included files have a direct dependence on 'math.h'. Any ideas where I could look for the underlying issue?

Thanks in advance

**Comment by Syniurge** [comment]
That's what I was referring to in #99 :

> Unfortunately the build fails because of a libc import, which I inadvertently broke with d6341da .

My apologies, I shouldn't have broken the master branch like that.
Although there are already tests for the C++ standard library, I need to add C standard lib tests too to ensure that this doesn't happen anymore.

I will fix this ASAP, hopefully tonight.

Meanwhile reverting d6341da should work:
```bash
git revert d6341da8f11d564e8d2d91f5299f6d0b8eb8324d
```
(but d6341da isn't the problem, the problem is that C allows macros and different types of symbols to bear the same name, while D doesn't)

**Comment by infinityplusb** [comment]
Sorry, I understand now! I'll try pull the reverted branch and see if that fixes my issue enough to progress!

**Comment by Syniurge** [comment]
Fixed! And took the oath to make master stable enough for general usage.
