### ISSUE TITLE
OSX build fails after update to llvm 5.0.1

### ISSUE THREAD

**Issue by timotheecour** [Syniurge/Calypso#101]
```
git clone --recursive https://github.com/Syniurge/Calypso
cd Calypso
mkdir build && cd build
cmake -G Ninja -DLLVM_CONFIG=$homebrew_D/Cellar/llvm/5.0.1/bin/llvm-config ..
ninja
```

Undefined symbols for architecture x86_64:
  "std::__1::error_code::message() const", referenced from:
      llvm::errorToErrorCode(llvm::Error) in libLLVMSupport.a(Error.cpp.o)
Error: /usr/bin/gcc failed with status: 1

NOTE: something suspicious is that previously, clang was being built before building bin/ldmd2, whereas now it tries to build bin/ldmd2 directly

**Comment by Syniurge** [comment]
On Linux too ldmd2 is being built right at the start of a parallel build.
I think the reason why ldmd2 is being built earlier than during a typical (upstream) ldc build is because ldmd2 is (and always has been) independent from ldc2, and during a Calypso build ldc2 depends on Clang, so before building ldc2 ninja waits for the submodule build to finish.

After reviewing the changes Calypso has made to CMakeLists.txt and comparing the logs of Travis for LDC 1.7 and Calypso builds I don't really know why Calypso builds now fail on OS X, and unfortunately the French Guiana submarine cable is still not repaired so my MacInCloud is still unusable. 

libc++ doesn't seem to get linked against, or if the ldmd2 host compiler does add it (I'll check tomorrow) there may be an inline namespace difference (the `__1`s).

**Comment by timotheecour** [comment]
will keep open until staging is merged into master

**Comment by Syniurge** [comment]
Merged.
