### ISSUE TITLE
Libstdc++ array error (happens in other libs)

### ISSUE THREAD

**Issue by wilsonk** [Syniurge/Calypso#14]
Hello Elie,

When trying to compile the array.h libstdc++ example we get this error:

/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/bits/exception_ptr.h(116): Error: class cpp.std.__exception_ptr.exception_ptr.exception_ptr identity assignment operator overload is illegal

and a few very similar errors (along with this same error) occur when trying to compile some other libs. I just thought I would document it here to make it somewhat of a priority.

Thanks,
Kelly

**Comment by Syniurge** [comment]
C++11 support is blocked by the heavy usage of template argument deduction by libstdc++, and trying to devise a more global hack to recover symbols in the deduced arguments made my brain implode because there are just too many cases and C++11 libstdc++ is a huge web of templates. This can probably be overcome but for the time being I'd rather focus on pre-C++11 support.

**Comment by Syniurge** [comment]
C++11 support is looking much better now, array.d is compiling. I think we should have another go at the libstdc++ examples, remove obsolete comments about ancient failures and complete the C++11 examples. Will post a commit cleaning some of the comments and fixing list.d soon.
