### ISSUE TITLE
is there an up to date document that contains C++ features support + limitations?

### ISSUE THREAD

**Issue by timotheecour** [Syniurge/Calypso#51]
Eg, I'd like to know whether this could work with things like:

```
stdio.h
opencv2/opencv.hpp
<boost>
```

I'm sure others are wondering too

## EDIT: summarizing from answers below

- [ ] a proper test suite
- [ ] finish MSVC support (catching exceptions)
- [ ] dtor calls by the GC
- [x] copy ctor calls for function arguments => done recent commits
- [ ] documentation
- [ ] more testing with more libraries and platforms (esp. OS X).

=> https://github.com/Syniurge/Calypso/blob/master/README.md#missing-features

**Comment by Syniurge** [comment]
Hi,

Sorry I managed to miss your issue. Documentation is basically non-existing, but a short up-to-date summary can be found on the wiki : https://wiki.dlang.org/Calypso

```
stdio.h
```
Works, C is easy to support.
```
opencv2/opencv.hpp
```
OpenCV 3.x should work, my experience with it is still limited to tinkering but here's a piece of working code: https://paste.kde.org/piyy8eadx

The one thing to keep in mind is that copy ctors do not get automatically called yet, which is why all the `Mat` function parameters are `ref`.

```
<boost>
```
Ogre3D relies on a couple of Boost libraries (thread and datetime iirc), which helped fix a few bugs. But no idea about the rest of Boost.

I'm not yet confident enough to say that Calypso is ready for general usage, but it's getting close. It still needs to catch up with LDC 1.3 (the switch to DDMD having been done last month, the tough part is behind), a proper test suite, finish MSVC support (catching exceptions), implement the missing essential features (dtor calls by the GC, copy ctor calls for function arguments), documentation, and more testing with more libraries and platforms (esp. OS X).

If you have a true OpenCV project in mind and give Calypso a try, shall you find any bug I'll be happy to hunt them in short delays.

**Comment by timotheecour** [comment]
putting the list in git repo makes sense to keep in sync with code changes
=> https://github.com/Syniurge/Calypso/blob/master/README.md#missing-features

**Comment by timotheecour** [comment]
> The one thing to keep in mind is that copy ctors do not get automatically called yet, which is why all the Mat function parameters are ref.

that has been fixed since then
