### ISSUE TITLE
ldc2 basics.cpp.o deletes source file basics.cpp

### ISSUE THREAD

**Issue by timotheecour** [Syniurge/Calypso#59]
following instructions from https://github.com/Syniurge/Calypso#specific-flags-and-building-the-basic-example :
```
cd Calypso/tests/calypso
clang++ -std=c++11 -c basics.cpp -o basics.cpp.o
path_to_build/ldc2 -cpp-args -std=c++11 basics.cpp.o -L-lstdc++ basics.d
#this deletes basics.cpp
```

EDIT: `basics.cpp` doesn't get deleted if i instead write:

```
clang++ -std=c++11 -c basics.cpp -o basics2.cpp.o
path_to_build/ldc2 -cpp-args -std=c++11 basics2.cpp.o -L-lstdc++ basics.d
```

EDIT: IIRC same issue on ubuntu

**Comment by Syniurge** [comment]
Actually it's LDC which infers the executable path from the first passed object file (so here basics.cpp.o is first -> basics.cpp is inferred as the executable name), and removes it before linking.
The command line wasn't correct, instead it should have been:
```
ldc2 -cpp-args -std=c++11  -L-lstdc++ basics.d basics.cpp.o
```
which prevents basics.cpp from being deleted. But in any case it's wrong, since basics.d modmaps basics.cpp now -> #62.

**Comment by timotheecour** [comment]
thanks, filed https://issues.dlang.org/show_bug.cgi?id=18275
